import Link from "next/link";
import { Button } from "~/components/ui/button";
import {
  Card,
  CardDescription,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { getUser } from "~/lib/supabase/server";

const steps = [
  {
    number: "01",
    title: "Find your problem",
    description:
      "Search by title, browse by difficulty, or let AI suggest a problem based on what you want to practise.",
  },
  {
    number: "02",
    title: "Work through the problem",
    description:
      "Read the problem, think it through, and get as far as you can on your own before reaching for a hint.",
  },
  {
    number: "03",
    title: "Unlock hints one by one",
    description:
      "Reveal up to 3 progressive hints at your own pace. Each one nudges you forward without giving the game away.",
  },
];

const features = [
  {
    title: "AI-Powered Hints",
    description:
      "Three progressive hints pre-generated by AI for each problem, calibrated to your skill level. Each one nudges your thinking without handing you the answer.",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
      >
        <path d="M12 2a7 7 0 0 1 7 7c0 2.6-1.4 4.9-3.5 6.2V17a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1v-1.8A7 7 0 0 1 12 2z" />
        <path d="M9 21h6M10 17h4" />
      </svg>
    ),
  },
  {
    title: "Problem Tracking",
    description:
      "Every problem you open is saved to your history. Rate hints, leave notes, and pick up exactly where you left off.",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
      >
        <path d="M9 11l3 3L22 4" />
        <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11" />
      </svg>
    ),
  },
  {
    title: "Skill Progression",
    description:
      "Your rating updates as you solve. The AI uses your level to calibrate hint depth — more nudge, less lecture.",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
      >
        <polyline points="22 7 13.5 15.5 8.5 10.5 2 17" />
        <polyline points="16 7 22 7 22 13" />
      </svg>
    ),
  },
  {
    title: "Solution Library",
    description:
      "Once you've solved a problem, browse community solutions in C++, Python, Java, and JavaScript with explanations.",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
      >
        <polyline points="16 18 22 12 16 6" />
        <polyline points="8 6 2 12 8 18" />
      </svg>
    ),
  },
];

export default async function Home() {
  const user = await getUser();

  return (
    <main className="mx-auto flex max-w-3xl flex-col gap-20 px-6 py-16">
      {/* Hero */}
      <section className="flex flex-col items-center gap-6 text-center">
        <div className="inline-flex items-center rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">
          For competitive programmers
        </div>
        <h1 className="text-5xl font-bold tracking-tight">
          Think sharper.
          <br />
          Solve harder.
        </h1>
        <p className="max-w-lg text-lg text-muted-foreground">
          AlgoPath analyses your exact attempt and delivers AI-powered,
          progressive hints that guide your thinking — not your clipboard. Built
          for programmers who want to genuinely improve, not just reach an
          answer.
        </p>
        <div className="flex flex-wrap items-center justify-center gap-3">
          <Button asChild size="lg">
            <Link href={user ? "/display-problem" : "/auth/login"}>
              {user ? "Go to problems" : "Get started free"}
            </Link>
          </Button>
          {!user && (
            <Button asChild variant="outline" size="lg">
              <Link href="/display-problem">Browse problems</Link>
            </Button>
          )}
        </div>
        <p className="text-xs text-muted-foreground">
          Supports LeetCode · Codeforces · custom problems
        </p>
      </section>

      {/* How it works */}
      <section className="flex flex-col gap-6">
        <div className="text-center">
          <h2 className="text-2xl font-semibold tracking-tight">
            How it works
          </h2>
          <p className="mt-2 text-muted-foreground">
            Three steps from question to solution.
          </p>
        </div>
        <div className="grid gap-px border border-border bg-border sm:grid-cols-3">
          {steps.map((step) => (
            <div
              key={step.number}
              className="flex flex-col gap-2 bg-background p-6"
            >
              <span className="font-mono text-xs text-muted-foreground">
                {step.number}
              </span>
              <h3 className="font-semibold">{step.title}</h3>
              <p className="text-sm text-muted-foreground">
                {step.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Hint preview */}
      <section className="flex flex-col gap-6">
        <div className="text-center">
          <h2 className="text-2xl font-semibold tracking-tight">
            Progressive hints, not spoilers
          </h2>
          <p className="mt-2 text-muted-foreground">
            Hint 1 observes. Hint 2 directs. Hint 3 outlines. None of them hand
            you the answer.
          </p>
        </div>
        <div className="overflow-hidden rounded-xl border">
          <div className="flex items-center gap-1.5 border-b bg-muted/50 px-4 py-3">
            <span className="size-3 rounded-full bg-destructive/60" />
            <span className="size-3 rounded-full bg-yellow-400/60" />
            <span className="size-3 rounded-full bg-green-500/60" />
            <span className="ml-3 font-mono text-xs text-muted-foreground">
              hint-engine — AlgoPath
            </span>
          </div>
          <div className="flex flex-col gap-4 p-5 font-mono text-sm">
            <div className="flex items-center gap-2 text-muted-foreground">
              <span className="text-green-500">▶</span>
              <span>Generating hint 1 of 3...</span>
            </div>
            <div className="rounded-lg border bg-muted/40 px-4 py-3">
              <p className="mb-1.5 font-mono text-xs text-muted-foreground">
                HINT_01 / OBSERVATION
              </p>
              <p className="font-sans text-sm leading-relaxed">
                Think about what data structure allows O(1) average lookups. As
                you iterate, can you instantly check whether the complement of
                the current element has already been seen?
              </p>
            </div>
            <div className="rounded-lg border bg-muted/40 px-4 py-3 opacity-40">
              <p className="mb-1.5 font-mono text-xs text-muted-foreground">
                HINT_02 / APPROACH
              </p>
              <p className="font-sans text-sm leading-relaxed text-muted-foreground">
                Locked — reveal when you're ready.
              </p>
            </div>
            <div className="flex gap-2 text-xs text-muted-foreground">
              <span className="rounded border px-2 py-1">reveal hint 2 →</span>
              <span className="rounded border px-2 py-1">rate usefulness</span>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="flex flex-col gap-6">
        <div className="text-center">
          <h2 className="text-2xl font-semibold tracking-tight">
            Everything you need to level up
          </h2>
          <p className="mt-2 text-muted-foreground">
            Built around the way competitive programmers actually work.
          </p>
        </div>
        <div className="grid gap-4 sm:grid-cols-2">
          {features.map((feature) => (
            <Card key={feature.title}>
              <CardHeader>
                <div className="flex size-9 items-center justify-center rounded-lg bg-muted text-foreground">
                  {feature.icon}
                </div>
                <CardTitle className="mt-2">{feature.title}</CardTitle>
                <CardDescription>{feature.description}</CardDescription>
              </CardHeader>
            </Card>
          ))}
        </div>
      </section>

      {/* Closing CTA */}
      <section className="flex flex-col items-center gap-4 rounded-xl border border-border px-6 py-14 text-center">
        <h2 className="text-2xl font-semibold tracking-tight">
          Start solving harder problems today.
        </h2>
        <p className="max-w-sm text-muted-foreground">
          Create a free account and get AI-guided hints tailored to your
          attempt. No credit card required.
        </p>
        <Button asChild size="lg">
          <Link href={user ? "/display-problem" : "/auth/login"}>
            {user ? "Go to problems" : "Get started free"}
          </Link>
        </Button>
      </section>
    </main>
  );
}
